//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class graphics extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private JTextArea jcomp3;
    private JTextField jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JLabel jcomp7;
    private JLabel jcomp8;
    private JLabel jcomp9;
    private JComboBox Algoritme;
    private JLabel jcomp11;

    public graphics() {
        //construct preComponents
        String[] AlgoritmeItems = {"Size", "Numeriek", "First-pick"};

        //construct components
        jcomp1 = new JButton ("uitvoeren");
        jcomp2 = new JButton ("bestand kiezen");
        jcomp3 = new JTextArea (5, 5);
        jcomp4 = new JTextField (5);
        jcomp5 = new JLabel ("order:");
        jcomp6 = new JLabel ("Resultaten: ");
        jcomp7 = new JLabel ("size: 0 sec, 0 dozen");
        jcomp8 = new JLabel ("Numeriek: 0 sec, 0 dozen");
        jcomp9 = new JLabel ("First-pick: 0 sec, 0 dozen");
        Algoritme = new JComboBox (AlgoritmeItems);
        jcomp11 = new JLabel ("Algoritme:");

        //set components properties
        Algoritme.setToolTipText ("Algoritme");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 398));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);
        add (Algoritme);
        add (jcomp11);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (555, 325, 100, 20);
        jcomp2.setBounds (535, 120, 120, 20);
        jcomp3.setBounds (20, 10, 405, 250);
        jcomp4.setBounds (25, 280, 195, 80);
        jcomp5.setBounds (485, 120, 40, 20);
        jcomp6.setBounds (260, 275, 75, 30);
        jcomp7.setBounds (260, 300, 115, 20);
        jcomp8.setBounds (260, 320, 145, 20);
        jcomp9.setBounds (260, 340, 145, 20);
        Algoritme.setBounds (555, 30, 100, 25);
        jcomp11.setBounds (480, 30, 65, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("graphics");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new graphics());
        frame.pack();
        frame.setVisible (true);
    }
}
