//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class JPanel extends JPanel {
    private JButton jcomp1;
    private JTextArea jcomp2;
    private JTextField jcomp3;
    private JLabel jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JLabel jcomp7;
    private JLabel jcomp8;
    private JComboBox Algoritme;
    private JLabel jcomp10;
    private JMenuBar jcomp11;

    public JPanel() {
        //construct preComponents
        String[] AlgoritmeItems = {"Size", "Numeriek", "First-pick"};
        JMenu bestand_kiezenMenu = new JMenu ("Bestand kiezen");
        JMenuItem xml_order1Item = new JMenuItem ("XML-order1");
        bestand_kiezenMenu.add (xml_order1Item);
        JMenuItem xml_order2Item = new JMenuItem ("XML-order2");
        bestand_kiezenMenu.add (xml_order2Item);

        //construct components
        jcomp1 = new JButton ("uitvoeren");
        jcomp2 = new JTextArea (5, 5);
        jcomp3 = new JTextField (5);
        jcomp4 = new JLabel ("order:");
        jcomp5 = new JLabel ("Resultaten: ");
        jcomp6 = new JLabel ("size: 0 sec, 0 dozen");
        jcomp7 = new JLabel ("Numeriek: 0 sec, 0 dozen");
        jcomp8 = new JLabel ("First-pick: 0 sec, 0 dozen");
        Algoritme = new JComboBox (AlgoritmeItems);
        jcomp10 = new JLabel ("Algoritme:");
        jcomp11 = new JMenuBar();
        jcomp11.add (bestand_kiezenMenu);

        //set components properties
        Algoritme.setToolTipText ("Algoritme");

        //adjust size and set layout
        setPreferredSize (new Dimension (667, 398));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (Algoritme);
        add (jcomp10);
        add (jcomp11);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (555, 325, 100, 20);
        jcomp2.setBounds (20, 10, 405, 250);
        jcomp3.setBounds (25, 280, 195, 80);
        jcomp4.setBounds (485, 125, 40, 20);
        jcomp5.setBounds (260, 275, 75, 30);
        jcomp6.setBounds (260, 300, 115, 20);
        jcomp7.setBounds (260, 320, 145, 20);
        jcomp8.setBounds (260, 340, 145, 20);
        Algoritme.setBounds (555, 30, 100, 25);
        jcomp10.setBounds (480, 30, 65, 25);
        jcomp11.setBounds (540, 125, 110, 20);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("JPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new JPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
